export const frequent = {
  "Alap élelmiszer": [
    "liszt",
    "cukor",
    "só",
    "tojás",
    "rizs",
    "humusz",
    "tagliatelle",
    "olaj",
    "ecet",
    "tonhal",
    "zöldséges tonhal",
    "kávé - plikkes",
    "coffetta",
    "kávé - örölt",
    "víz",
    "szeletelt kenyér",
    "oliva olaj",
    "oliva bogyó",
    "felvágottak",
    "kávé - instant",
    "prézli",
    "hambi szósz",
    "mustár",
    "majonéz",
    "ketchup",
    "paradicsom paszta",
    "bab konzerv",
    "kukorica konzerv",
    "borsó konzerv",
    "tonhal",
    "kókusz tej",
    "mogyoró",
    "szotyi",
    "tökmag",
    "ramen",
    "müzliszelet",
    "popcorn",
    "pisztácia",
    "édesítőszer",
  ],
  tejtermékek: [
    "tej",
    "vaj",
    "sajt",
    "szeletelt sajt",
    "lapka sajt",
    "tejföl",
    "görög joghurt",
    "kefir",
    "sana",
    "tömlős krémsajt",
    "főzőtejszín",
    "mozzarella",
    "feta",
    "reszelt sajt",
    "tejföl krém",
  ],
  "zöldség + gyümölcs": [
    "sárgarépa",
    "hagyma",
    "krumpli",
    "paprika",
    "uborka",
    "paradicsom",
    "zeller",
    "káposzta",
    "cherry paradicsom",
    "citrom",
    "lime",
    "saláta",
    "fokhagyma",
    "zöldhagyma",
    "gomba",
    "banán",
    "petrezselyem",
    "petrezselyem zöld",
  ],
  fagyasztott: [
    "zöldség mix",
    "leveles lap",
    "őrőlt hús",
    "fagyi",
    "pizza",
    "halfilé",
    "fornetti",
    "zöld borsó",
    "spenót",
    "csirke filé",
    "pizza",
    "szalma krumpli",
    "leveles tészta",
  ],
  "vegyi + ipari": [
    "mosókapszula",
    "öblítő",
    "kékszesz",
    "cif",
    "mosogató szivacs",
    "konyhai papírtörlő",
    "szemetes zsák",
    "mosogatószer",
    "wc papír",
    "szappan",
    "lefolyótisztító",
    "vízkőoldó",
    "foltkivevő",
    "padlótisztító",
    "bref",
    "nedves laveta",
    "betét",
    "tisztasági betét",
    "tampon",
    "nedves törlőkendő",
    "dobozos pzs",
  ],
  fűszerek: [
    "pirospaprika",
    "oregánó",
    "bazsalikom",
    "kömény",
    "szerecsendió",
    "gyömbérpor",
    "rozmaring",
    "kapor",
    "szezámmag",
    "babérlevél",
    "fokhagymapor",
    "hagymapor",
    "garam masala",
    "curry",
    "chili",
    "fekete bors",
    "vegeta",
  ],
};
