export const frequent = {
  dairyAndRefrigerated: [
    "tej",
    "vaj",
    "sajt",
    "tejföl",
    "joghurt",
    "túró",
    "margarin",
    "tojás",
    "készételek",
    "kefir",
    "tejszín",
    "krémsajt",
    "vajkrém",
    "kakaó",
    "puding",
    "desszert",
    "főzőtejszín",
    "laktózmentes tej",
    "natúr joghurt",
    "gyümölcsjoghurt",
    "parenyica",
    "trappista sajt",
    "edami sajt",
    "mozzarella",
    "feta",
    "camembert",
    "brie",
    "kockasajt",
    "körözött",
    "kecskesajt",
    "krémtúró",
    "túrórudi",
  ],
  frozenFood: [
    "fagyasztott zöldségkeverék",
    "fagyasztott húsok",
    "jégkrém",
    "fagyasztott pizza",
    "fagyasztott gyümölcsök",
    "fagyasztott burgonya",
    "fagyasztott hal",
    "fagyasztott pékáru",
    "fagyasztott borsó",
    "fagyasztott kukorica",
    "fagyasztott spenót",
    "fagyasztott brokkoli",
    "fagyasztott karfiol",
    "fagyasztott csirke",
    "fagyasztott halfilé",
    "fagyasztott pizza",
    "fagyasztott hasábburgonya",
    "fagyasztott pogácsa",
    "fagyasztott leveles tészta",
    "fagyasztott palacsinta",
    "fagyasztott gomba",
    "fagyasztott pulyka",
    "fagyasztott zöldbab",
    "fagyasztott lasagne",
    "fagyasztott készétel",
  ],
  cleaningSupplies: [
    "mosószer",
    "öblítő",
    "tisztítószerek",
    "felmosószer",
    "ablaktisztító",
    "súrolószer",
    "fertőtlenítő",
    "szivacs",
    "törlőkendő",
    "szemetes zsák",
    "mosogatószer",
    "wc papír",
    "papírtörlő",
    "mosogatókefe",
    "mosogatógép tabletta",
    "mosógél",
    "szappan",
    "lefolyótisztító",
    "porzsák",
    "illatosító",
    "sütőtisztító",
    "vízkőoldó",
    "por",
    "gumikesztyű",
    "mosópor",
    "mosószappan",
    "mosóparfüm",
    "mosóháló",
    "szárító kendő",
    "szivacs törlő",
    "padlótisztító",
    "konyhai törlőkendő",
    "wc illatosító",
    "mosógép tisztító",
    "mosogatógép só",
    "mosogatógép öblítő",
    "ablaktisztító kendő",
    "porzsák",
    "szőnyegtisztító",
    "bútorápoló",
    "porrongy",
  ],
  freshProduce: [
    "alma",
    "banán",
    "paradicsom",
    "uborka",
    "burgonya",
    "hagyma",
    "répa",
    "paprika",
    "citrom",
    "narancs",
    "saláta",
    "fokhagyma",
    "káposzta",
    "karalábé",
    "zeller",
    "cékla",
    "retek",
    "spenót",
    "brokkoli",
    "karfiol",
    "zöldbab",
    "zöldborsó",
    "eper",
    "szőlő",
    "barack",
    "körte",
    "málna",
    "ribizli",
    "sárgarépa",
    "petrezselyem",
    "zöldhagyma",
    "fejes saláta",
    "jégsaláta",
    "avokádó",
    "kivi",
    "ananász",
    "mangó",
    "grapefruit",
    "lime",
    "padlizsán",
    "cukkini",
    "tök",
    "spárga",
    "gomba",
    "őszibarack",
    "meggy",
    "cseresznye",
    "dinnye",
    "sárgadinnye",
    "görögdinnye",
    "szilva",
    "feketeribizli",
    "áfonya",
    "mandarin",
    "gránátalma",
    "datolya",
    "füge",
    "kókusz",
    "pisztácia",
    "mogyoró",
    "dió",
    "mandula",
    "kesudió",
    "tökmag",
    "napraforgómag",
    "mazsola",
    "aszaltszilva",
    "aszaltsárgabarack",
    "gyömbér",
    "csicsóka",
    "édesburgonya",
    "lila hagyma",
    "póréhagyma",
    "zöldségmix",
    "zöldsaláta",
    "rukola",
    "madársaláta",
    "bazsalikom",
    "menta",
    "koriander",
    "kapor",
    "rozmaring",
    "tárkony",
    "oregánó",
    "petrezselyemzöld",
    "snidling",
    "torma",
    "chili paprika",
    "jalapeno",
    "piros paprika",
    "sárga paprika",
    "zöld paprika",
    "fehér paprika",
    "koktélparadicsom",
    "paradicsomfürt",
    "paradicsompüré",
  ],
  pantryItems: [
    "liszt",
    "cukor",
    "só",
    "rizs",
    "tészta",
    "olaj",
    "ecet",
    "konzerv",
    "fűszerek",
    "kávé",
    "tea",
    "búzadara",
    "zsemlemorzsa",
    "sütőpor",
    "szódabikarbóna",
    "élesztő",
    "kakaópor",
    "lekvár",
    "méz",
    "mustár",
    "majonéz",
    "paradicsompüré",
    "paradicsomszósz",
    "babkonzerv",
    "kukoricakonzerv",
    "borsókonzerv",
    "hal konzerv",
    "tonhal konzerv",
    "csicseriborsó konzerv",
    "lencse",
    "zabpehely",
    "müzli",
    "granola",
    "keksz",
    "ropi",
    "chips",
    "sós mogyoró",
    "napraforgómag",
    "tökmag",
    "aszalványok",
    "szárított paradicsom",
    "szárított gomba",
    "szárított gyümölcs",
    "instant leves",
    "porleves",
    "szószpor",
    "alaplé",
    "leveskocka",
    "csokoládé",
    "édesség",
    "cukorka",
    "sütemény",
    "keksz",
    "nápolyi",
    "müzliszelet",
    "sós rúd",
    "kréker",
    "popcorn",
    "pudingpor",
    "vaníliás cukor",
    "fahéj",
    "bors",
    "pirospaprika",
    "oregánó",
    "bazsalikom",
    "majoránna",
    "kömény",
    "szegfűszeg",
    "szerecsendió",
    "gyömbérpor",
    "koriander",
    "tárkony",
    "rozmaring",
    "kapor",
    "szezámmag",
    "lenmag",
    "chia mag",
    "kókuszreszelék",
    "mandula",
    "dió",
    "mogyoró",
    "kesudió",
    "pisztácia",
    "földimogyoró",
    "mazsola",
    "aszaltszilva",
    "aszaltsárgabarack",
    "kandírozott gyümölcs",
    "instant kávé",
    "őrölt kávé",
    "kapszulás kávé",
    "filteres tea",
    "gyümölcstea",
    "zöld tea",
    "fekete tea",
    "herba tea",
    "kakaó italpor",
    "forró csoki por",
    "instant kakaó",
    "cukorhelyettesítő",
    "édesítőszer",
    "stevia",
    "eritrit",
    "xilit",
    "szirup",
    "agave szirup",
    "juharszirup",
    "rizstej",
    "mandulatej",
    "szója tej",
    "kókusztej",
    "zabtej",
    "kondenzált tej",
    "sűrített tej",
    "tejpor",
    "babérlevél",
    "mustármag",
    "borsikafű",
    "csili por",
    "fokhagymapor",
    "hagymapor",
    "levespor",
    "szárított petrezselyem",
    "szárított kapor",
    "szárított bazsalikom",
    "szárított oregánó",
    "szárított rozmaring",
    "szárított kakukkfű",
    "szárított majoránna",
    "szárított tárkony",
    "szárított zeller",
    "szárított zöldségkeverék",
    "szárított gomba",
    "szárított paradicsom",
    "szárított gyümölcs",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
    "szárított sárgabarack",
    "szárított szilva",
    "szárított alma",
    "szárított körte",
    "szárított barack",
    "szárított szilva",
    "szárított meggy",
    "szárított cseresznye",
    "szárított áfonya",
    "szárított ribizli",
    "szárított málna",
    "szárított eper",
    "szárított szeder",
    "szárított feketeribizli",
    "szárított vörösáfonya",
  ],
};
